import withMDX from "@next/mdx";

const oldPaths = [
  "/gallery/portable-asphalt-mixer-exporter",
  "/blog/advantages-atlas-wet-mix-macadam-plant",
  "/blog/6-tph-bitumen-decanter-export-to-nepal",
  "/blog/concrete-mixer-effective-functioning-minimal-downtime",
  "/asphalt-mixing-plant.Two",
  "/kerb-cutting-machine/kerb-cutting-7-4hp",
  "/gallery/asphalt-batch-mix-plant-160-tph-india",
  "/images/download_files/304244921.pdf",
  "/blog/2024/11",
  "/blog/2022/05",
  "/blog/2023/12",
  "/blog/2024/10",
  "/blog/2025/06",
  "/blog/2023/01",
  "/blog/top-features-concrete-plant",
  "/blog/2025/07",
  "/blog/2024/04",
  "/blog/2024/09",
  "/blog/2022",
  "/blog/advantages-mobile-drum-mix-plant",
  "/blog/maximum-output-mechanical-broom",
  "/video_case_study.php",
  "/images/case_study/539864636.pdf",
  "/gallery/planta-de-asfalto",
  "/blog/how-to-save-money-on-concrete",
  "/blog/concrete-batching-plant-characteristics",
  "/blog/what-advance-technology-does-the-top-asphalt-batch-mix-plant-factory-have",
  "/blog/ready-mix-concrete-process",
  "/blog/advantages-atlas-mobile-concrete-plant",
  "/blog/features-components-asphalt-batch-plants",
  "/gallery/wet-mix-plant-libya",
  "/images/case_study/409979632.pdf",
  "/blog/counterflow-asphalt-plant-spain",
  "/blog/ready-mix-concrete-advantages",
  "/images/case_study/127709618.pdf",
  "/blog/high-performance-mobile-drum-mixers-algeria",
  "/gallery/asphalt-batch-mix-plant-myanmar",
  "/blog/mini-batching-plant",
  "/asphalt-batch-mix-",
  "/images/case_study/656236740.pdf",
  "/images/case_study/747133991.pdf",
  "/images/download_files/45557891.pdf",
  "/asphalt-plants/stationary-asphalt-batching-plant/abp-80-mixer-1000kg-twin-shaft-mixer-60-80-tph",
  "/blog/counterflow-asphalt-",
  "/asphalt-mixing-",
  "/gallery/counterflow-asphalt-plant-in-malaysia",
  "/kerb-cutting-machine/kerb-cutting-heavy-duty",
  "/blog/reasons-to-buy-atlas-asphalt-drum-mix-plant",
  "/gallery/asphalt-batching-plant-for-sale",
  "/gallery/160-tph-asphalt-batching-plant-exporter",
  "/gallery/asphalt-batch-mix-plant-supplier",
  "/blog/conveyor-belt-upkeep-getting-rid-of-functional-issues",
  "/images/case_study/14993991.pdf",
  "/gallery/mobile-asphalt-drum-mix-plant-philippines",
  "/gallery/drum-mix-plant-nigeria",
  "/gallery/asphalt-drum-mix-plant-nigeria",
  "/gallery/counterflow-asphalt-drum-plant",
  "/blog/components-atlas-wmm-plants",
  "/images/download_files/475671574.pdf",
  "/blog/a-comprehensive-guide-to-concrete-batch-plants",
  "/gallery/single-drum-counter-flow-plant-near-phalodi-india",
  "/gallery/drum-mix-asphalt-plant-in-philippines",
  "/gallery/port",
  "/blog/importance-of-preventive-maintenance-for-your-equipment",
  "/blog/abp-120-premium-packs-punch",
  "/blog/bitumen-drum-decanter-working-principle",
  "/blog/characteristic-features-concrete-batching-plants",
  "/blog/containerized-bitumen-decanter-export-to-congo",
  "/blog/anatomy-bitumen-pressure-distributor",
  "/asphalt-mixing-plantStationary",
  "/blog/260-tph-asphalt-batch-plant-customer-success-stories",
  "/images/download_files/970788411.pdf",
  "/blog/counterflow-asphalt-mix-plant-with-rap",
  "/gallery/180-tph-asphalt-mixing-plant-india",
  "/images/case_study/417354727.pdf",
  "/images/case_study/370409518.pdf",
  "/blog/bitumen-decanter",
  "/asphalt-mixing-plantIt",
  "/blog/comparison-road-cleaning-machines",
  "/blog/soil-stabilization-plants-for-road-projects",
  "/gallery/portable-asphalt-plant-india",
  "/gallery/asphalt-batch-plant-jaipur-india",
  "/blog/category/road-sweeping-machines",
  "/gallery/160-tph-tower-asphalt-plant-kalyan-thane-india",
  "/gallery/asphalt-drum-plant-philippines",
  "/gallery/portable-asphalt-plants-india",
  "/images/download_files/538087075.pdf",
  "/gallery/bitumen-drum-melting-equipment",
  "/gallery/semi-mobile-asphalt-mix-plant-morocco",
  "/images/download_files/420575737.pdf",
  "/images/case_study/439466916.pdf",
  "/gallery/for-sale-asphalt-mixing-plant",
  "/gallery/portable-drum-mixer-tanzania",
  "/gallery/tower-asphalt-plant",
  "/images/download_files/443923617.pdf",
  "/images/download_files/237555937.pdf",
  "/images/download_files/531215342.pdf",
  "/products/stationary-abp",
  "/gallery/case_study.html",
  "/road-sweeping-equipment",
  "/catch/concrete-plants",
  "/gallery/dm-plant-wmm-plant-libya",
  "/gallery/portable-asphalt-drum-mix-plant-botswana",
  "/gallery/bitumen-sprayer-manufacturers",
  "/gallery/180-tph-hot-asphalt-batching-plant",
  "/gallery/mobile-asphalt-mix-plant-philippines",
  "/gallery/asphalt-mixing-plant-philippines-160-tph",
  "/images/case_study/783869631.pdf",
  "/gallery/wmm-plant-suppliers-india",
  "/images/download_files/534856391.pdf",
  "/gallery/double-drum-asphalt-mixer-india",
  "/gallery/small-asphalt-drum-mixer-myanmar",
  "/blog/how-does-asphalt-drum-mix-plant-operate",
  "/catch/asphalt-drum-mix-plant",
  "/images/download_files/660214140.pdf",
  "/images/download_files/702960323.pdf",
  "/gallery/drummed-asphalt-melter-oman",
  "/gallery/hot-mix-plant-manufacturer-india",
  "/gallery/260-tph-hot-asphalt-batch-plant",
  "/f/special/refill",
  "/gallery/bitumen-drum-melting-unit-india",
  "/case_study.html",
  "/gallery/160-tph-asphalt-batching-mixing-plant-aurangabad",
  "/gallery/double-drum-asphalt-mix-plant-manufacturer-india",
  "/gallery/tower-unit-mobile-asphalt-batch-plant",
  "/gallery/asphalt-mixing-plant-nashik",
  "/gallery/asphalt-mixer-india",
  "/gallery/mobile-hot-mix-plant",
  "/gallery/asphalt-batching-plant-nashik",
  "/photo-gallery",
  "/case_studies.php",
  "/gallery/mobile-asphalt-mixing-plant-price",
  "/gallery/asphalt-batch-plant",
  "/gallery/soil-stabilization-plant-india",
  "/gallery/wet-mix-macadam-plant-uae",
  "/video-gallery",
  "/about-us",
  "/blog/tag/asphalt-drum-mix-plant",
  "/blog/best-hydraulic-broom-maintenance-tips",
  "/gallery/asphalt-batching-plant-india",
  "/blog/2024/07",
  "/blog/tag/concrete-mixer",
  "/blog/2021/06",
  "/blog/tag/counterflow-asphalt-plant",
  "/blog/2021/04",
  "/blog/2024/08",
  "/blog/2024/03",
  "/gallery/asphalt-batch-mix-plant",
  "/gallery/hot-mix-asphalt-plant",
  "/catch/asphalt-batch-mix-plant",
  "/images/download_files/46141103.pdf",
  "/blog/tag/small-scale-construction-companies",
  "/catch/bitumen-pressure-distributor",
  "/business_opportunity.php",
  "/images/download_files/301030932.pdf",
  "/gallery/portable-asphalt-mixing-plant-manufacturer",
  "/business-opportunity",
  "/about_us.php",
  "/catch/mobile-asphalt-plant",
  "/concrete-batching-plant",
  "/video_gallery.php",
  "/catch/products",
  "/blog/2021/05",
  "/ctg/search/searchByKeywordDetailConditionView",
  "/blog/2023/05",
  "/gallery/asphalt-mixing-plant-nigeria",
  "/products.php",
  "/catch/bitumen-decanting-machine",
  "/blog/tag/asphalt-plant-installation",
  "/ctg/search/searchByCtgView/company-profile.pdf",
  "/f/special/stampink/company-profile.pdf",
  "/e/13/company-profile.pdf",
  "/blog/2024/page/2",
  "/f/special/hakui/company-profile.pdf",
  "/f/special/isetan/company-profile.pdf",
  "/f/calculator/calculator00/company-profile.pdf",
  "/f/partition/partition00/company-profile.pdf",
  "/iqr/refitInputView/company-profile.pdf",
  "/e/15/company-profile.pdf",
  "/e/07/company-profile.pdf",
  "/f/detergent/detergent00/company-profile.pdf",
  "/guide/policy/browser/company-profile.pdf",
  "/blog/2023/07",
  "/blog/2024/01",
  "/e/25/company-profile.pdf",
  "/f/towel/towel00/company-profile.pdf",
  "/guide/policy/company-profile.pdf",
  "/webapp/shops-club/servlet/company-profile.pdf",
  "/f/timecard/timecard00/company-profile.pdf",
  "/catch/asphalt-mixing-plant",
  "/blog/tag/drum-mix-plants-in-oman",
  "/photo_gallery.php",
  "/mechanical-broom",
  "/hydraulic-broom",
  "/catch/counterflow-asphalt-mixer",
  "/road-sweepers",
  "/mobile-concrete-mixers",
  "/portable-concrete-batch-plant",
  "/catch/drummed-bitumen-decanting-machine",
  "/e/09/company-profile.pdf",
  "/e/22/company-profile.pdf",
  "/catch/portable-asphalt-plant",
  "/blog/what-is-batching-plant-capacity",
  "/blog/mini-concrete-batch-plants-features-benefits",
  "/images/download_files/506823476.pdf",
  "/blog/importance-of-stock-spares-for-asphalt-batch-mix-plant",
  "/blog/advantages-mobile-concrete-batching-plants",
  "/blog/features-benefits-continuous-twin-shaft-mixers",
  "/double-drum-asphalt-plant",
  "/mobile-concrete-batching-plant",
  "/portable-batch-mix-plant",
  "/mini-concrete-batching-plant",
  "/counter-flow-asphalt-plant",
  "/mobile-asphalt-batch-plants",
  "/mobile-asphalt-drum-mix-plant",
  "/mini-concrete-plant-diesel",
  "/e/26/company-profile.pdf",
  "/stationary-concrete-batching-plant",
  "/e/06/company-profile.pdf",
  "/e/23/company-profile.pdf",
  "/double-drum-asphalt-plant.html",
  "/blog/2025/09",
  "/images/download_files/228836955.pdf",
  "/gallery/260-tph-asphalt-batch-mixing-plant",
  "/gallery/tar-sprayer-for-sale",
  "/e/10/company-profile.pdf",
  "/ol/0/company-profile.pdf",
  "/blog/[slug]",
];

const customRedirects = [
  // ===== Phase 3 — Batch 2: legacy URLs → contextual 301 (was homepage redirect) =====
  { source: "/blog/facts-about-bitumen-tanks", destination: "/bitumen-decanter" },
  { source: "/blog/mechanical-road-sweeper-for-road-cleaning", destination: "/other-products/hydraulic-broomer" },
  { source: "/blog/bitumen-sprayer-features-advantages-components", destination: "/bitumen-sprayer" },
  { source: "/blog/11-ways-to-store-aggregates-effectively", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/blog/types-road-cleaning-brooms", destination: "/other-products/hydraulic-broomer" },
  { source: "/blog/way-an-asphalt-plant-functions", destination: "/asphalt-plants" },
  { source: "/blog/bitumen-tanks-for-sale", destination: "/bitumen-decanter" },
  { source: "/blog/concrete-batching-plant-for-philippines", destination: "/concrete-plants/stationary-concrete-batching-plant" },
  { source: "/blog/comparison-concrete-plants-with-twin-shaft-mixer-and-reversible-mixer", destination: "/concrete-plants" },
  { source: "/blog/anatomy-mini-bitumen-sprayer", destination: "/mini-bitumen-sprayer" },
  { source: "/blog/atlas-asphalt-batch-plant-gujarat", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/blog/some-secrets-why-customers-love-atlas", destination: "/about" },
  { source: "/blog/why-customers-prefer-atlas-technologies", destination: "/about" },
  { source: "/blog/concrete-batching-plant-size", destination: "/concrete-plants/stationary-concrete-batching-plant" },
  { source: "/blog/top-quality-road-cleaning-equipment", destination: "/other-products/hydraulic-broomer" },
  { source: "/blog/types-of-batching-plants", destination: "/asphalt-plants" },
  { source: "/blog/wet-mix-plants-for-better-less-expensive-alternative", destination: "/wet-mix-plant" },
  { source: "/blog/40-60-tph-mobile-asphalt-drum-mix-plant-philippines", destination: "/asphalt-plants/mobile-asphalt-drum-mix-plant" },
  { source: "/blog/asphalt-drum-mix-plant-for-oman", destination: "/asphalt-plants/asphalt-drum-mix-plant" },
  { source: "/blog/asphalt-drum-mix-plant-layout", destination: "/asphalt-plants/asphalt-drum-mix-plant" },
  { source: "/blog/features-components-asphalt-batch-plant", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/blog/asphalt-plant-site-visit", destination: "/about" },
  { source: "/blog/essential-batch-asphalt-plant-parts", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/blog/portable-concrete-mixer-industrial-park-india", destination: "/concrete-mixer" },
  { source: "/blog/mechanism-of-pollution-coontrol-devices-in-asphalt-plants", destination: "/asphalt-plants" },
  { source: "/blog/plc-and-microprocessor-control-panel", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/blog/drum-type-concrete-mixers", destination: "/concrete-mixer" },
  { source: "/blog/faq-concrete-batch-mixing-plants", destination: "/concrete-plants/stationary-concrete-batching-plant" },
  { source: "/blog/growth-strategies-small-construction-companies", destination: "/blog" },
  { source: "/downloads", destination: "/about" },
  { source: "/company-profile.pdf", destination: "/about" },

  // ===== Phase 3 — Batch 1: legacy URLs → contextual 301 (was homepage redirect) =====
  { source: "/concrete-kerb-laying-machine", destination: "/other-products/kerb-laying-machine" },
  { source: "/mobile-batch-mix-plant", destination: "/asphalt-plants/mobile-asphalt-batching-plant" },
  { source: "/asphalt-batch-mix-plant", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/wet-mix-macadam-wmm-plant", destination: "/wet-mix-plant" },
  { source: "/mini-concrete-batch-plant", destination: "/concrete-plants/mini-concrete-batching-plant" },
  { source: "/portable-asphalt-plant", destination: "/asphalt-plants/mobile-asphalt-drum-mix-plant" },
  { source: "/bitumen-decanters", destination: "/bitumen-decanter" },
  { source: "/asphalt-mixing-plant", destination: "/asphalt-plants" },
  { source: "/asphalt-batching-plant", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/asphalt-drum-mix-plant", destination: "/asphalt-plants/asphalt-drum-mix-plant" },
  { source: "/asphalt-batching-plant-manufacturers", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/mobile-concrete-batch-mix-plant", destination: "/concrete-plants/mobile-concrete-batching-plant-twin-shaft-mixer" },
  { source: "/drummed-bitumen-decanting-machine", destination: "/bitumen-decanter" },
  { source: "/counterflow-asphalt-mixer", destination: "/asphalt-plants/counter-flow-asphalt-plant" },
  { source: "/mobile-asphalt-mixing-plants", destination: "/asphalt-plants/mobile-asphalt-batching-plant" },
  { source: "/mobile-asphalt-plant", destination: "/asphalt-plants/mobile-asphalt-drum-mix-plant" },
  { source: "/portable-concrete-plant", destination: "/concrete-plants/mobile-concrete-batching-plant-twin-shaft-mixer" },
  { source: "/bitumen-pressure-distributor", destination: "/bitumen-sprayer" },
  { source: "/inline-concrete-batching-plant", destination: "/concrete-plants/stationary-concrete-batching-plant" },
  { source: "/batch-asphalt-mixing-plants", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/asphalt-drum-mixers", destination: "/asphalt-plants/asphalt-drum-mix-plant" },
  { source: "/portable-concrete-batch-mix-plant", destination: "/concrete-plants/mobile-concrete-batching-plant-twin-shaft-mixer" },
  { source: "/bitumen-decanting-machine", destination: "/bitumen-decanter" },
  { source: "/blog/understanding-asphalt-mixing-plant-layout", destination: "/asphalt-plants" },
  { source: "/blog/asphalt-batch-mix-plant-process", destination: "/asphalt-plants/stationary-asphalt-batching-plant" },
  { source: "/blog/asphalt-batch-plant-vs-drum-plant", destination: "/blog/how-to-choose-right-asphalt-plant" },
  { source: "/blog/counterflow-asphalt-plants", destination: "/asphalt-plants/counter-flow-asphalt-plant" },
  { source: "/blog/counterflow-asphalt-plants-atlas", destination: "/asphalt-plants/counter-flow-asphalt-plant" },
  { source: "/blog/reversible-drum-in-ready-mix-concrete-plants", destination: "/concrete-plants/reversible-mixer-concrete-plant" },
  { source: "/blog/types-of-asphalt-mixing-plants-batch-plant-drum-mix-plant", destination: "/blog/how-to-choose-right-asphalt-plant" },
  { source: "/blog/mobile-asphalt-plant-details", destination: "/asphalt-plants/mobile-asphalt-batching-plant" },

  { source: "/asphalt-plants/asphalt-mixing-plant", destination: "/asphalt-plants" },
  { source: "/asphalt-machines", destination: "/asphalt-plants" },
  { source: "/asphalt-machines/asphalt-machines1", destination: "/asphalt-plants" },

  // URL restructure — Bitumen Decanter moved out of /asphalt-machines
  { source: "/asphalt-machines/bitumen-decanter", destination: "/bitumen-decanter" },
  { source: "/asphalt-machines/bitumen-decanter/acm-4", destination: "/bitumen-decanter/acm-4" },
  { source: "/asphalt-machines/bitumen-decanter/acm-7", destination: "/bitumen-decanter/acm-7" },
  { source: "/asphalt-machines/bitumen-decanter/acm-9", destination: "/bitumen-decanter/acm-9" },
  { source: "/asphalt-machines/bitumen-decanter/acm-11", destination: "/bitumen-decanter/acm-11" },
  {
    source: "/asphalt-machines/bitumen-decanter/drum-decanters",
    destination: "/bitumen-decanter",
    permanent: true,
  },
  {
    source: "/bitumen-decanter/drum-decanters",
    destination: "/bitumen-decanter",
    permanent: true,
  },

  // URL restructure — Bitumen Sprayer moved out of /asphalt-machines
  { source: "/asphalt-machines/bitumen-sprayer", destination: "/bitumen-sprayer" },
  { source: "/asphalt-machines/bitumen-sprayer/ae-4000", destination: "/bitumen-sprayer/ae-4000" },
  { source: "/asphalt-machines/bitumen-sprayer/ae-6000", destination: "/bitumen-sprayer/ae-6000" },
  { source: "/asphalt-machines/bitumen-sprayer/ae-8000", destination: "/bitumen-sprayer/ae-8000" },
  { source: "/asphalt-machines/bitumen-sprayer/ae-10000", destination: "/bitumen-sprayer/ae-10000" },
  { source: "/asphalt-machines/bitumen-sprayer/ae-12000", destination: "/bitumen-sprayer/ae-12000" },
  { source: "/asphalt-machines/bitumen-sprayer/hyd-hopper-electric-model", destination: "/bitumen-sprayer/hyd-hopper-electric-model" },

  // URL restructure — Mini Bitumen Sprayer moved out of /asphalt-machines
  { source: "/asphalt-machines/mini-bitumen-sprayer", destination: "/mini-bitumen-sprayer" },
  { source: "/asphalt-machines/mini-bitumen-sprayer/ai-3000", destination: "/mini-bitumen-sprayer/ai-3000" },

  // URL restructure — Wet Mix Plant moved out of /asphalt-machines
  { source: "/asphalt-machines/wet-mix-plant", destination: "/wet-mix-plant" },
  { source: "/asphalt-machines/wet-mix-plant/wm-100", destination: "/wet-mix-plant/wm-100" },
  { source: "/asphalt-machines/wet-mix-plant/wm-160", destination: "/wet-mix-plant/wm-160" },
  { source: "/asphalt-machines/wet-mix-plant/wm-200", destination: "/wet-mix-plant/wm-200" },
  { source: "/asphalt-machines/wet-mix-plant/wm-250", destination: "/wet-mix-plant/wm-250" },
  { source: "/asphalt-machines/wet-mix-plant/wm-300", destination: "/wet-mix-plant/wm-300" },

  {
    source: "/concrete-plants/mobile-concrete-batching-plant-pan-mixer",
    destination: "/concrete-plants/stationary-concrete-batching-plant-pan-mixer",
  },
  {
    source: "/concrete-plants/mobile-concrete-batching-plant-planetary-mixer",
    destination: "/concrete-plants/stationary-concrete-batching-plant-planetary-mixer",
  },
  {
    source: "/blog/road-sweeping-machine-sustainable-road-maintenance",
    destination: "/blog/hydraulic-broomer-vs-mechanical-broomer",
  },
];

const nextConfig = {
  reactStrictMode: true,
  compress: true,
  pageExtensions: ["js", "jsx", "mdx"],
  images: {
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 60 * 60 * 24 * 30,
  },
  async redirects() {
    return [
      ...customRedirects.flatMap(({ source, destination }) => [
        { source, destination, permanent: true },
        {
          source: source.endsWith("/") ? source : source + "/",
          destination,
          permanent: true,
        },
      ]),
      ...oldPaths.flatMap((path) => [
        { source: path, destination: "/", permanent: true },
        {
          source: path.endsWith("/") ? path : path + "/",
          destination: "/",
          permanent: true,
        },
      ]),
    ];
  },
};

export default withMDX({ extension: /\.mdx?$/ })(nextConfig);
